app/soil/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, FloatField,SelectMultipleField, DateTimeField,DateField,SelectField
from wtforms.validators import DataRequired, InputRequired, ValidationError

class SoilplotForm(FlaskForm):
	id=IntegerField('ID')
	action=IntegerField('action')
	frequency=IntegerField('采样频率',validators=[DataRequired()])
	plotname=StringField('样地名称', validators=[DataRequired()])
	region=SelectField('区域', coerce=str,validators=[DataRequired()])
	latdegree=IntegerField('度',validators=[DataRequired()])
	latminute=IntegerField('分',validators=[DataRequired()])
	latsecond=FloatField('秒',validators=[InputRequired()])
	londegree=IntegerField('度',validators=[DataRequired()])
	lonminute=IntegerField('分',validators=[DataRequired()])
	lonsecond=FloatField('秒',validators=[InputRequired()])
	altitude=IntegerField('高程')
	submit=SubmitField('提交')

class SoildataqueryForm(FlaskForm):
	action=IntegerField('action')
	plots=SelectMultipleField('样地',coerce=int,validators=[DataRequired()])
	indicators=SelectMultipleField('指标',coerce=int,validators=[DataRequired()])
	years=SelectMultipleField('年份',coerce=int,validators=[DataRequired()])
	submit=SubmitField('查询')

class SoilindicatorForm(FlaskForm):
	id=IntegerField('ID')
	action=IntegerField('action')
	indicatorname=StringField('指标名称',validators=[DataRequired()])
	symbol=StringField('符号')
	unit=StringField('单位')
	dland_standard=FloatField('建设用地管控标准值')
	aland_standard_ph1=FloatField('PH<=5.5')
	aland_standard_ph2=FloatField('5.5&lt;PH<=6.5')
	aland_standard_ph3=FloatField('6.5&lt;PH<=7.5')
	aland_standard_ph4=FloatField('PH>=7.5')
	indicatortype=SelectField('指标类型')
	submit=SubmitField('提交')
	

app/soil/__init__.py
from flask import Blueprint

bp=Blueprint('soil',__name__)

from app.soil import routes

app/soil/routes.py
import os
import json
from app.soil.forms import SoilplotForm,SoildataqueryForm,SoilindicatorForm
from app.models import Soilplot,Soilindicator,Soildata
from flask import render_template, flash, redirect, url_for, request, current_app, send_file, send_from_directory
from app import db
from werkzeug.urls import url_parse
from werkzeug import secure_filename
import xlrd
import re
from datetime import date,datetime
from app.soil import bp
from flask_login import current_user,login_required

ALLOWED_EXTENSIONS=set(['txt','pdf','png','jpg','jpeg','gif','xls','xlsx','csv'])

@bp.route("/plot",methods=["GET","POST"])
@login_required
def plot():
	if not current_user.check_roles(['admin','soil']):
		flash('您无权访问该页面')
		return redirect(url_for('main.index'))
	form=SoilplotForm()
	form.region.choices=[('北仑城区网格化采样','北仑城区网格化采样'),('城郊乡梯度流域采样','城郊乡梯度流域采样')]
	if request.method=='POST' and (form.action.data is not None):
		if form.action.data==3:#action: '0' for ADD, '1' for EDIT, '2' for 'DELETE', '3' for excel file upload
			file=request.files['file']
			if file and allowed_file(file.filename):
				filename=secure_filename(file.filename)
				filepath=os.path.join(current_app.config['UPLOAD_FOLDER'],filename)
				file.save(filepath)
				workbook=xlrd.open_workbook(filepath)
				hassheet=False
				for sheetname in workbook.sheet_names():
					if sheetname.find('土壤调查样点')>=0:
						result=insert_soilplots(sheet=workbook.sheet_by_name(sheetname),workbook=workbook)
						if result>0:
							flash('数据上传完成，已成功添加数据 {} 条'.format(str(result)))
						elif result==0:
							flash('数据上传完成，未添加任何数据')
						else:
							flash('数据上传失败')
						hassheet=True
				if hassheet==False:
					flash('上传文件中未找到表 “土壤调查样点”。请上传规范格式的文件，具体请参考模板。')
			else:
				flash('出错：请上传规范格式的文件，具体请参考模板。')	
		elif form.action.data==2:
			plot=Soilplot.query.filter_by(id=form.id.data).first()
			if plot is None:
				flash('样地删除失败！')
			else:
				for data in plot.soildatas:
					db.session.delete(data)
				db.session.delete(plot)
				db.session.commit()
				flash('土壤样地 <{}> 删除成功！'.format(plot.plotname))
		elif form.action.data==0:
			plot=Soilplot(plotname=form.plotname.data,\
				region=form.region.data,\
				frequency=form.frequency.data,\
				latdegree=form.latdegree.data,\
				latminute=form.latminute.data,\
				latsecond=form.latsecond.data,\
				londegree=form.londegree.data,\
				lonminute=form.lonminute.data,\
				lonsecond=form.lonsecond.data,\
				altitude=form.altitude.data)
			db.session.add(plot)
			db.session.commit()
			flash('土壤样地 <{}> 添加成功！'.format(form.plotname.data))
		elif form.action.data==1:
			plot=Soilplot.query.filter_by(id=form.id.data).first()
			if plot:
				plot.region=form.region.data
				plot.frequency=form.frequency.data
				plot.latdegree=form.latdegree.data
				plot.latminute=form.latminute.data
				plot.latsecond=form.latsecond.data
				plot.londegree=form.londegree.data
				plot.lonminute=form.lonminute.data
				plot.lonsecond=form.lonsecond.data
				plot.altitude=form.altitude.data
				db.session.commit()
				flash('土壤样地 <{}> 编辑成功！'.format(form.plotname.data))
			else:
				flash('样地数据编辑失败！')
	plots=Soilplot.query.order_by(Soilplot.plotname).all()
	return render_template('soil/plot.html',title='土壤调查样地信息',plots=plots, form=form)

@bp.route('/clearplots')
@login_required
def clearplots():
	if not current_user.check_roles(['admin','soil']):
		flash('您无权访问该页面')
		return redirect(url_for('main.index'))
	cleardata(Soildata)
	cleardata(Soilplot)
	flash('已清空土壤调查样地数据')
	return redirect(url_for('soil.plot'))

@bp.route('/download_plotexample', methods=['GET'])
@login_required
def download_plotexample():
	if not current_user.check_roles(['admin','soil']):
		flash('您无权访问该页面')
		return redirect(url_for('main.index'))
	filename='soilplots_example.xlsx'
	filepath=os.path.join(current_app.config['DOWNLOAD_FOLDER'])
	return send_from_directory(directory=filepath, filename=filename)

@bp.route('/download_dataexample', methods=['GET'])
@login_required
def download_dataexample():
	if not current_user.check_roles(['admin','soil']):
		flash('您无权访问该页面')
		return redirect(url_for('main.index'))
	filename='soildata_example.xlsx'
	filepath=os.path.join(current_app.config['DOWNLOAD_FOLDER'])
	return send_from_directory(directory=filepath, filename=filename)

def cleardata(dbmodel):
	datas=dbmodel.query.all()
	for data in datas:
		db.session.delete(data)
	db.session.commit()

def allowed_file(filename):
	return '.' in filename and filename.rsplit('.',1)[1] in ALLOWED_EXTENSIONS

def insert_soilplots(sheet,workbook):
	nrows=sheet.nrows
	count=0
	#try:
	while True:
		for i in range(1,nrows):
			row_values=sheet.row_values(i)
			plot=Soilplot.query.filter_by(plotname=row_values[0].strip(' ')).first()
			if plot is None:
				plot=Soilplot()
				plot.plotname=row_values[0].strip(' ')
				if sheet.cell(i,4).ctype==2:
					plot.frequency=int(row_values[4])
				plot.region=row_values[3].strip(' ')
				m1=re.match("(\\d+)°(\\d+)'(\\d+\\.?\\d*)\"",row_values[1].strip(' '))
				if m1:
					plot.londegree=int(m1.group(1))
					plot.lonminute=int(m1.group(2))
					plot.lonsecond=float(m1.group(3))
				m2=re.match("(\\d+)°(\\d+)'(\\d+\\.?\\d*)\"",row_values[2].strip(' '))
				if m2:
					plot.latdegree=int(m2.group(1))
					plot.latminute=int(m2.group(2))
					plot.latsecond=float(m2.group(3))
				db.session.add(plot)
				count=count+1
		db.session.commit()
		return count
	#except:
	#	return -1

@bp.route('/data',methods=['GET','POST'])
@login_required
def data():
	if not current_user.check_roles(['admin','soil']):
		flash('您无权访问该页面')
		return redirect(url_for('main.index'))
	form=SoildataqueryForm()
	form.plots.choices=[(plot.id,plot.plotname) for plot in Soilplot.query.all()]
	#form.years.choices=[(item.year,str(item.year)) for item in Soildata.query.group_by(Soildata.year).all()]
	soildatas=Soildata.query.order_by(Soildata.year).all()
	form.years.choices=[]
	existyear=None
	if len(soildatas)>0:
		existyear=soildatas[0].year
		for item in soildatas:
			if item.year!=existyear:
				form.years.choices.append((existyear,str(existyear)))
				existyear=item.year
		form.years.choices.append((existyear,str(existyear)))
	form.indicators.choices=[(indicator.id,indicator.indicatorname) for indicator in Soilindicator.query.all()]
	soildatas=[]
	indicators=[]
	plots=[]
	years=[]
	if request.method=='POST' and request.form['action']:
		if request.form['action']=='0':#action: '0' for EXCEL FILE UPLOAD, '1' for QUERY
			file=request.files['file']
			if file and allowed_file(file.filename):
				filename=secure_filename(file.filename)
				filepath=os.path.join(current_app.config['UPLOAD_FOLDER'],filename)
				file.save(filepath)
				workbook=xlrd.open_workbook(filepath)
				hassheet=False
				for sheetname in workbook.sheet_names():
					try:
						year=int(sheetname)
					except:
						year=-1
					if year>=0:
						added_indicators=check_indicators(sheet=workbook.sheet_by_name(sheetname),workbook=workbook)
						if len(added_indicators)>0:
							flash('已添加指标项 {} 共{}项'.format('，'.join(added_indicators),len(added_indicators)))
						result=insert_soildatas(sheet=workbook.sheet_by_name(sheetname),workbook=workbook,year=year)
						if result[0]>0:
							str1='数据上传完成，共上传数据 {} 条。'.format(str(result[1]+result[2]))
							str2=''
							if result[2]>0:
								str2='{} 条数据已存在，跳过未添加。'.format(str(result[2]))
							if result[1]>0:
								db.session.commit()
								str3='已成功添加数据 {} 条。'.format(str(result[1]))
							elif result[1]==0:
								str3='未添加任何数据。'
							flash(str1+str2+str3)
						else:
							flash('数据上传失败！'+result[1])
						hassheet=True
						#form.years.choices=[(item.year,str(item.year)) for item in Soildata.query.group_by(Soildata.year).all()]
						sdatas=Soildata.query.order_by(Soildata.year).all()
						form.years.choices=[]
						existyear=None
						if len(sdatas)>0:
							existyear=sdatas[0].year
							for item in sdatas:
								if item.year!=existyear:
									form.years.choices.append((existyear,str(existyear)))
									existyear=item.year
							form.years.choices.append((existyear,str(existyear)))
						form.indicators.choices=[(indicator.id,indicator.indicatorname) for indicator in Soilindicator.query.all()]
				if hassheet==False:
					flash('上传文件中未找到以年份命名的数据表。请上传规范格式的文件，具体请参考模板。')
			else:
				flash('出错：请上传规范格式的文件，具体请参考模板。')
		elif form.action.data==1:
			plots=Soilplot.query.filter(Soilplot.id.in_(form.plots.data)).all()
			indicators=Soilindicator.query.filter(Soilindicator.id.in_(form.indicators.data)).order_by(Soilindicator.id).all()
			years=form.years.data
			for plot in plots:
				for year in years:
					data=Soildata.query.filter_by(plot=plot).filter_by(year=year).filter(Soildata.indicator_id.in_(form.indicators.data)).all()
					if data:
						soildata=[plot,year,data]
						soildatas.append(soildata)
	return render_template('soil/data.html',title='土壤调查数据',form=form,datas=soildatas,indicators=indicators,plots=plots,years=years)

@bp.route('/deldata',methods=['POST'])
@login_required
def deldata():
	if not current_user.check_roles(['admin','soil']):
		flash('您无权访问该页面')
		return redirect(url_for('main.index'))
	try:
		plotid=request.form['plotid']
		year=request.form['year']
		indicatorid=request.form['indicatorid']
		plotids=request.form['plots']
		years=request.form['years']
		indicatorids=request.form['indicators']
		plotids=json.loads(plotids)
		years=json.loads(years)
		indicatorids=json.loads(indicatorids)
		if indicatorid=='0':
			datas=Soildata.query.filter(Soildata.soilplot_id==plotid,Soildata.year==year,Soildata.indicator_id.in_(indicatorids)).all()
			if datas is None:
				return 'fail'
			else:
				for item in datas:
					db.session.delete(item)
				db.session.commit()
		else:
			data=Soildata.query.filter(Soildata.soilplot_id==plotid,Soildata.indicator_id==indicatorid,Soildata.year==year).first()
			if data is None:
				return 'fail'
			else:
				db.session.delete(data)
				db.session.commit()
		soildatas=[]

app/templates/soil/_addtimeModal.html
<div class="modal fade" id="addtimeModal" tabindex="-1" role="dialog" aria-labelledby="addtimeModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form action="addyear" method='POST'>
				<div class="modal-header">
					<a class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></a>
					<h4 class="modal-title" id="myModalLabel">添加监测年份</h4>
				</div>
				<div class="modal-body">
					<p>
						<b>年份 </b><input id="time-to-add" name="year" value="" type="text"><span id="addtime-error" style="color:red; display:none;">[年份输入格式错误]</span>
					</p>
				</div>
				<div class="modal-footer">
					<button id="add-cancel" type="button" class="btn btn-default" data-dismiss="modal">取消</button>
					<input id="add-confirm" type="submit" class="btn btn-primary" value="添加">
				</div>
			</form>
		</div>
	</div>
</div>

app/templates/soil/_datas.html
<table class="panel-heading" style="width:100%;">
	<tr>
		<td style="text-align:left; padding-left:15px;">
			<h4>数据面板</h4>
		</td>
		<td style="text-align:right; padding-right:15px;">
			<a class="btn btn-primary import" style="height:24px; vertical-align:center; padding-top:0; padding-bottom:0;" href="#" data-toggle="modal" data-target="#uploadModal">导入</a>
		</td>
	</tr>
</table>
<table class="table">
	<tr>
		<th scope="col">序号</th>
		<th scope="col">监测点</th>
		<th scope="col">年份</th>
		{% for item in indicators %}
		<th scope="col">
			<span>{{ item.indicatorname }}</span>
			{% if item.unit %}
			<br>
			<span>({{ item.unit }})</span>
			{% endif %}
		</th>
		{% endfor %}
		<th scope="col">操作</th>
	</tr>
	
	{% for item in datas %}
	<tr id="row-{{ loop.index }}" scope="row">
		<td>
			{{ loop.index }}
			<span id="rowid" style="display:none;">row-{{ loop.index }}</span>
		</td>
		<td>
			<span id="plotid" style="display:none;">{{ item[0].id }}</span>
			<span id="plotname">{{ item[0].plotname }}</span>
		</td>
		<td>
			<span id="year">{{ item[1] }}</span>
		</td>
		{% for indicator in indicators %}
		<td>
			<span id="{{ indicator.id }}">
			{% for data in item[2] %}
			{% if data.indicator==indicator %}
			{{ data.value }}
			{% endif %}
			{% endfor %}
			</span>
		</td>
		{% endfor %}			
		<td>
			<a class="edit" href="#" data-toggle="modal" data-target="#editdataModal">编辑</a> | 
			<a class="del" href="#" data-toggle="modal" data-target="#delModal">删除</a>
		</td>
	</tr>
	{% endfor %}
</table>

app/templates/soil/_deldatamodal.html
<div class="modal fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="delModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
				<div class="modal-header">
					<a class="close" data-dismiss="modal" aira-label="Close"><span aria-hidden="true">&times;</span></a>
					<h4 class="modal-title" id="delModalLabel">删除数据</h4>
				</div>
				<div class="modal-body">
					<p>
						<b>样点：</b>
						<span id="del-plot"></span>
						<span style="display:none;" id="del-plot-id"></span>
					</p>
					<p>
						<b>年份：</b>
						<span id="del-year"></span>
					</p>
					<p>
						<b>指标：</b>
						<select id="del-indicator" name="del-indicator">
							<option value="0">全部</option>
							{% for item in indicators %}
							<option value="{{ item.id }}">{{ item.indicatorname }}</option>
							{% endfor %}
						</select>
					</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default form-clearerrorinfo" data-dismiss="modal">取消</button>
					<button id="del-confirm" type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
				</div>
			</form>
		</div>
	</div>
</div>

app/templates/soil/_deltimeModal.html
<div class="modal fade" id="deltimeModal" tabindex="-1" role="dialog" aria-labelledby="deltimeModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form action="delyear" method='POST'>
				<div class="modal-header">
					<a class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></a>
					<h4 class="modal-title" id="deltimeModalLabel">删除确认</h4>
				</div>
				<div class="modal-body">
					<p class="del-message">
						确定删除<b>{{year}}年</b>的所有数据吗？
						<input id="year-to-del" name="year" value="{{ year }}" type="text" style="display:none;">
					</p>
				</div>
				<div class="modal-footer">
					<button id="del-cancel" type="button" class="btn btn-default" data-dismiss="modal">取消</button>
					<input id="del-confirm" type="submit" class="btn btn-primary" value="确定">
				</div>
			</form>
		</div>
	</div>
</div>

app/templates/soil/_editdatamodal.html
<div class="modal fade" id="editdataModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<a class="close" data-dismiss="modal" aira-label="Close"><span aria-hidden="true">&times;</span></a>
				<h4 class="modal-title" id="editModalLabel">编辑数据</h4>
			</div>
			<div class="modal-body">
				<span style="display:none;" id="row-id"></span>
				<p>
					<b>样点：</b>
					<span id="edit-plot"></span>
					<span style="display:none;" id="edit-plot-id"></span>
				</p>
				<p>
					<b>年份：</b>
					<span id="edit-year"></span>
				</p>
				<p>
					<b>指标：</b>
					<select id="edit-indicator" name="edit-indicator">
						{% for item in indicators %}
						<option value="{{ item.id }}">{{ item.indicatorname }}</option>
						{% endfor %}
					</select>
				</p>
				<p>
					<b>数值：</b>
					<input id="edit-value" name="edit-value" size="6" value="" type="text"/>
				</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default form-clearerrorinfo" data-dismiss="modal">取消</button>
				<button id="edit-confirm" type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
			</div>
		</div>
	</div>
</div>

app/templates/soil/_plots.html
<table class="panel-heading" style="width:100%;">
	<tr>
		<td style="text-align:left; padding-left:15px;">
			<h4>数据面板</h4>
		</td>
		<td style="text-align:right; padding-right:15px;">
			<a class="btn btn-primary" style="height:24px; vertical-align:center; padding-top:0; padding-bottom:0;" id='btn-add' href="#" data-toggle="modal" data-target="#editModal" >添加</a>
			<a class="btn btn-primary import" style="height:24px; vertical-align:center; padding-top:0; padding-bottom:0;" href="#" data-toggle="modal" data-target="#uploadModal">导入</a>
			<a class="btn btn-primary" style="height:24px; vertical-align:center; padding-top:0; padding-bottom:0;" href="{{url_for('soil.clearplots')}}">清空</a></td>
		</td>
	</tr>
</table>
<table class="table">
	<tr>
		<th scope="col">序号</th>
		<th scope="col">样地编号</th>
		<th scope="col">区域</th>
		<th scope="col">经度</th>
		<th scope="col">纬度</th>
		<th scope="col">高程</th>
		<th scope="col">采样频率</th>
		<th scope="col">操作</th>
	</tr>
	{% for plot in plots %}
	<tr scope="row">
		<td style="padding-left:15px;">{{ loop.index }}</td>
		<td><span id="plotid" style="display:none;">{{ plot.id }}</span><span id="plotname">{{ plot.plotname }}</span></td>
		<td><span id="region">{{ plot.region }}</span></td>
		<td><span id="londegree">{{ plot.londegree }}</span>°<span id="lonminute">{{ plot.lonminute }}</span>'<span id="lonsecond">{{ plot.lonsecond }}</span>"</td>
		<td><span id="latdegree">{{ plot.latdegree }}</span>°<span id="latminute">{{ plot.latminute }}</span>'<span id="latsecond">{{ plot.latsecond }}</span>"</td>
		<td><span id="altitude">{{ plot.altitude }}</span></td>
		<td>1次/<span id="frequency">{{ plot.frequency }}</span>个月</td>
		<td><a class="edit" href="#"  data-toggle="modal" data-target="#editModal" >编辑</a> | <a class="del" href="#" data-toggle="modal" data-target="#delModal" >删除</a></td>
	</tr>
	{% endfor %}
</table>

app/templates/soil/_uploaddatamodal.html
<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<a class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></a>
				<h4 class="modal-title" id="uploadModalLabel">数据上传</h4>
			</div>
			<div class="modal-body">
				<form action="" method=post enctype=multipart/form-data>
					<p>
						<input id="action" name="action" value="0" type="text" style="display:none;">
						<input type='file' name='file'>
						<hr>
						<input type='submit' value="上传"> <input id='upload-cancel' type='button' data-dismiss="modal" value='取消'>
						<button id="uploadtip" type="button" class="btn btn-default btn-sm" title='请严格按照下载模板格式上传EXCEL数据。每一年数据保存在单独的Sheet里，Sheet名用4位数的年份表示。数据第一行是指标名，指标中文名和英文名用空格分隔开（如果有英文名的话）。数据第一列是样点编号。指标名请与之前上传的数据保持一致，否则将作为新的指标另外存储。' data-toggle="tooltip" data-placement="top" style="background-color:tranparent;">上传说明</button>
					</p>
					<p>
						<a id="downloadtemplate" target="_blank" href="{{ url_for('soil.download_dataexample') }}">下载模板文件</a>
					</p>
				</form>
			</div>
		</div>
	</div>
</div>

app/templates/soil/_uploadmodal.html
<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<a class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></a>
				<h4 class="modal-title" id="uploadModalLabel">数据上传</h4>
			</div>
			<div class="modal-body">
				<form action="" method=post enctype=multipart/form-data>
					<p>
						<input id="action" name="action" value="0" type="text" style="display:none;">
						<input type='file' name='file'>
						<hr>
						<input type='submit' data-dismiss='modal' value="上传"> <input id='upload-cancel' type='button' data-dismiss="modal" value='取消'>
						<button id="uploadtip" type="button" class="btn btn-default btn-sm" title='请严格按照下载模板格式上传EXCEL数据。' data-toggle="tooltip" data-placement="top" style="background-color:tranparent;">上传说明</button>
					</p>
					<p>
						<a id="downloadtemplate" target="_blank" href="{{ url_for('soil.download_dataexample') }}">下载模板文件</a>
					</p>
				</form>
			</div>
		</div>
	</div>
</div>

app/templates/soil/_uploadplotmodal.html
<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<a class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></a>
				<h4 class="modal-title" id="uploadModalLabel">数据上传</h4>
			</div>
			<div class="modal-body">
				<form action="" method=post enctype=multipart/form-data>
					<p>
						<input id="action" name="action" value="3" type="text" style="display:none;">
						<input type='file' name='file'>
						<hr>
						<input type='submit' value="上传"> <input id='upload-cancel' type='button' data-dismiss="modal" value='取消'>
						<button id="uploadtip" type="button" class="btn btn-default btn-sm" title='请严格按照下载模板格式上传EXCEL数据。建议以模板为基础进行填写，不要改变第一行（标题行）的内容。经纬度格式按度分秒填写（参照模板）。区域类型只能包含2类：“北仑城区网格化采样”和“城郊乡梯度流域采样”。“样点名称”如果已存在，则对应一条数据将不会被添加，其余数据可照常添加。' data-toggle="tooltip" data-placement="top" style="background-color:tranparent;">上传说明</button>
					</p>
					<p>
						<a id="downloadtemplate" target="_blank" href="{{ url_for('soil.download_plotexample') }}">下载模板文件</a>
					</p>
				</form>
			</div>
		</div>
	</div>
</div>